//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHomepage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public int Id { get; set; }
        public string Uri { get; set; }
        public Nullable<int> DisplayColumn { get; set; }
        public Nullable<int> DisplayRow { get; set; }
        public Nullable<int> DisplayItemCount { get; set; }
        public string FeedTitle { get; set; }
    }
}
